# Generated by Django 5.1.5 on 2025-01-23 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.JSONField(blank=True, default=list)),
                ('service_details', models.TextField(blank=True)),
                ('scheduled', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED')], default='PENDING', max_length=10, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hired', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hired_booking', to=settings.AUTH_USER_MODEL)),
                ('hiring', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
